Repository ISISComputingGroup/EPICS-refl, pull requests merged in 2020-08, with the labels that each got.

#5 Ticket3465 bench driver
  ReflectometryServer/__init__.py
  ReflectometryServer/axis.py
  ReflectometryServer/beam_path_calc.py
  ReflectometryServer/components.py
  ReflectometryServer/geometry.py
  ReflectometryServer/ioc_driver.py
  ReflectometryServer/test_modules/data_mother.py
  ReflectometryServer/test_modules/test_beam_path_calc.py
  ReflectometryServer/test_modules/test_components.py
  ReflectometryServer/test_modules/test_set_current_motor_position.py
Labels: size/XXL

#8 CA wait after setting velocity so move has new velocity every time
  ReflectometryServer/pv_wrapper.py
Labels: size/XS

#6 Ticket5455 park all axes
  ReflectometryServer/axis.py
  ReflectometryServer/beam_path_calc.py
  ReflectometryServer/components.py
  ReflectometryServer/ioc_driver.py
  ReflectometryServer/parameters.py
  ReflectometryServer/test_modules/test_beamline.py
  ReflectometryServer/test_modules/test_beamline_parameter.py
  ReflectometryServer/test_modules/test_components.py
Labels: size/L

#7 Make sure move has happened before set is finished
  ReflectometryServer/__init__.py
  ReflectometryServer/beamline.py
  ReflectometryServer/parameters.py
  ReflectometryServer/pv_wrapper.py
  ReflectometryServer/test_modules/test_set_current_motor_position.py
Labels: size/M

#9 Add param list PVs for parameter groups
  ReflectometryServer/ChannelAccess/pv_manager.py
  ReflectometryServer/parameters.py
Labels: size/M

#10 Add offset to out of beam position
  ReflectometryServer/axis.py
  ReflectometryServer/beam_path_calc.py
  ReflectometryServer/ioc_driver.py
  ReflectometryServer/out_of_beam.py
  ReflectometryServer/test_modules/test_ioc_driving_layer.py
  ReflectometryServer/test_modules/test_out_of_beam_lookup.py
Labels: size/L
