Repository ISISComputingGroup/EPICS-refl, pull requests merged in 2020-10, with the labels that each got.

#17 Do not restore velocity on init moving state
  ReflectometryServer/pv_wrapper.py
Labels: size/XS

#16 In vertical config use CHI and TRANS not POSITION and ANGLE
  ReflectometryServer/components.py
  ReflectometryServer/test_modules/data_mother.py
  ReflectometryServer/test_modules/test_components.py
Labels: size/L

#15 Axis out of beam still moves if component as a whole is not
  ReflectometryServer/ioc_driver.py
  ReflectometryServer/test_modules/test_beamline.py
Labels: size/M
