Repository ISISComputingGroup/EPICS-refl, pull requests merged in 2021-01, with the labels that each got.

#23 Ticket5783 parking sequence
  ReflectometryServer/__init__.py
  ReflectometryServer/axis.py
  ReflectometryServer/beam_path_calc.py
  ReflectometryServer/beamline.py
  ReflectometryServer/beamline_configuration.py
  ReflectometryServer/example_beamline.py
  ReflectometryServer/exceptions.py
  ReflectometryServer/file_io.py
  ReflectometryServer/ioc_driver.py
  ReflectometryServer/out_of_beam.py
  ReflectometryServer/pv_wrapper.py
  ReflectometryServer/test_modules/data_mother.py
  ReflectometryServer/test_modules/test_beamline.py
  ReflectometryServer/test_modules/test_beamline_parameter.py
  ReflectometryServer/test_modules/test_components.py
  ReflectometryServer/test_modules/test_engineering_corrections.py
  ReflectometryServer/test_modules/test_in_beam_manager.py
  ReflectometryServer/test_modules/test_ioc_driving_layer.py
  ReflectometryServer/test_modules/test_out_of_beam_lookup.py
  ReflectometryServer/test_modules/test_set_current_motor_position.py
  ReflectometryServer/test_modules/utils.py
Labels: size/XXL

#24 Ticket 5896: INTER long axis
  ReflectometryServer/axis.py
  ReflectometryServer/beam_path_calc.py
  ReflectometryServer/beamline.py
  ReflectometryServer/components.py
  ReflectometryServer/geometry.py
  ReflectometryServer/ioc_driver.py
  ReflectometryServer/movement_strategy.py
  ReflectometryServer/parameters.py
  ReflectometryServer/test_modules/test_beam_path_calc.py
  ReflectometryServer/test_modules/test_beamline.py
  ReflectometryServer/test_modules/test_beamline_parameter.py
  ReflectometryServer/test_modules/test_components.py
  ReflectometryServer/test_modules/test_ioc_driving_layer.py
  ReflectometryServer/test_modules/test_movement.py
  run_all_tests.py
Labels: size/XL

#25 Ticket6000 archive
  ReflectometryServer/ChannelAccess/pv_manager.py
  ReflectometryServer/server_status_manager.py
Labels: size/XS

#27 Add custom function that run when parameter is set
  ReflectometryServer/parameters.py
  ReflectometryServer/pv_wrapper.py
  ReflectometryServer/test_modules/test_beamline_parameter.py
  ReflectometryServer/test_modules/test_set_current_motor_position.py
Labels: size/L

#28 Skip failing test until it is merged as part of another ticket
  ReflectometryServer/test_modules/test_engineering_corrections.py
Labels: size/XS
